### ISSUE TITLE
Templates fot plots and tables

### ISSUE THREAD

**Issue by sebastian-loos** [openwashdata-dev/openwashdata#13]
Hey @larnsce,

For a more consistent look for the packages I mentioned templates/themes for plots today in the morning. 

I now went through the issues. If possible, we could integrate the plot and table templates into the pkgdown R package template you mentioned in [this issue](https://github.com/openwashdata/openwashdata/issues/8).

I don't think of this issue as a high priority, I just wanted to write down this Issue somewhere. And still, the longer we wait to set up rules, the more we have to adjust older packages etc.

What are you're thoughts? Also @mianzg and @mbannert.

**Comment by larnsce** [comment]
Thank you, @sebastian-loos. I agree that we should develop our own themes, especially for plots. It includes a few items that we need to work on in line with remaining "corporate identify".

- fonts
- color palettes
- plot types (line plot, bar plot, etc.)

Some resources:

- https://github.com/teunbrand/ggplot_tricks (I also like the look and feel of the plots)
- https://github.com/hrbrmstr/hrbrthemes (I love his work and the look of the plots)
