### ISSUE TITLE
Function: generate_roxygen_docs (Generate roxygen2 documentation from a CSV file)

### ISSUE THREAD

**Issue by larnsce** [openwashdata-dev/openwashdata#4]
# Function: `generate_roxygen_docs()` 

## **Pass In**

1. file name of dataset from [data-raw/dictionary.csv](https://github.com/openwashdata/fsmglobal/blob/main/data-raw/dictionary.csv) with relevant column file_name 
2. file path to [data-raw/dictionary.csv](https://github.com/openwashdata/fsmglobal/blob/main/data-raw/dictionary.csv) with relevant columns  variable_name, description 
3. file path and file name of output file [data/R/DATA.R](https://github.com/openwashdata/fsmglobal/blob/main/R/fsmglobal.R)
4. text string: description of data in maximum two sentences

## **Pass Out**

- R script with roxygen2 comments in data/R/DATA.R

The script output contains:

- line 1: name of data
- line 3: one to two sentence description on third line
- line 5: `@format` comment with sentence: A tibble with X rows and Y variables: (X and Y are populated from `data/DATA.rda` as counted in in generate_roxygen_docs function)
- line after closure `}` of `\describe{`: @source `{}`
- after final roxygen comment `#'`: the name of the data in quotes

## Complete examples: 

- https://github.com/openwashdata/fsmglobal/blob/main/R/fsmglobal.R
- https://github.com/Global-Health-Engineering/durbanplasticwaste/blob/main/R/litterboom_counts.R

## Current function:

- https://github.com/openwashdata/openwashdata/blob/main/R/generate_roxygen_docs.R

## Additional resources:

- https://jsta.rbind.io/blog/automated-roxygen-documentation-of-r-package-data/

**Comment by mbannert** [comment]
I've created a function that creates .R files to describe datasets. One can have multiple datasets per package. Some finetuning in writing the output file is necessary, but I feel it goes into the right direction. (inspired byt the fivethirtyeight dataset package. => in the end I'll go for a single data.R file per package.

**Comment by bonschorno** [comment]
Please review and close/raise issue for washr, @larnsce.

**Comment by larnsce** [comment]
Thanks, @bonschorno. This is covered with this function: https://github.com/openwashdata-dev/washr/blob/main/R/setup_roxygen.R
