### ISSUE TITLE
Function: get_variable_info() (Get variable information from a list of data frames)

### ISSUE THREAD

**Issue by larnsce** [openwashdata-dev/openwashdata#5]
# Function: `get_variable_info() ` 

## **Pass In**

- `@param` data A list of data frames
- `@param` directory A character vector of directory names corresponding to the data frames (default: "")
- `@param` file_name A character vector of file names corresponding to the data frames (default: "")

## **Pass Out**

- A dataframe with five columns: diretcory, file_name, variable_name, variable_type, description
- This is the data dictionary, which could then be written as a dictionary.csv or dictionary.xlsx if directly shared data donators to document the variables in the data

## Complete examples: 

- https://github.com/openwashdata/cbssuitabilityhaiti/blob/50e9833516e42a4bba3b35155969849c37c02c19/data-raw/dictionary.csv
- 
## Current function:

- https://github.com/openwashdata/cbssuitabilityhaiti/blob/50e9833516e42a4bba3b35155969849c37c02c19/data-raw/data_processing.R#L71

## Documentation

```
#' Get variable information from a list of data frames
#'
#' This function takes a list of data frames and extracts variable information,
#' such as directory, file name, variable name, and variable type. It returns
#' a tibble containing this information.
#'
#' @param data A list of data frames
#' @param directory A character vector of directory names corresponding to the data frames (default: "")
#' @param file_name A character vector of file names corresponding to the data frames (default: "")
#'
#' @return A tibble containing the variable information
#' @examples
#' data_list <- list(df1 = data.frame(x = 1:3, y = letters[1:3]),
#'                  df2 = data.frame(a = c(TRUE, FALSE), b = c(3.5, 4.2)))
#' variable_info <- get_variable_info(data_list, directory = c("dir1", "dir2"), file_name = c("file1", "file2"))
#' print(variable_info)
get_variable_info <- function(data, directory = "", file_name = "") {
  # Function implementation
}
```

**Comment by larnsce** [comment]
Link: https://github.com/openwashdata/book/issues/13#issuecomment-1621165618

**Comment by mbannert** [comment]
I've pushed a suggestion to the workflow branch. It recursively extract all files in the data folder and generates a pre-filled meta information skeleton. We could add some functionality to share those files via google sheets instead. That way we can collect meta information using google sheets as an interface to the original data provider. 

Let's discuss how / when we can merge workflow into main and from then on have main, dev + feature branches.

**Comment by larnsce** [comment]
@mbannert: What have you named this function in the `workflow` branch:

https://github.com/openwashdata-dev/openwashdata/tree/workflow/R
